/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AdminStatsResponse } from './models/admin-stats-response';
export type { ApiResponseAdminStatsResponse } from './models/api-response-admin-stats-response';
export type { ApiResponseAuthenticationResponse } from './models/api-response-authentication-response';
export type { ApiResponseBookResponse } from './models/api-response-book-response';
export type { ApiResponseBorrowedBookResponse } from './models/api-response-borrowed-book-response';
export type { ApiResponseFeedbackResponse } from './models/api-response-feedback-response';
export type { ApiResponseRegisterResponse } from './models/api-response-register-response';
export type { ApiResponseVoid } from './models/api-response-void';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BookRequest } from './models/book-request';
export type { BookResponse } from './models/book-response';
export type { BorrowedBookResponse } from './models/borrowed-book-response';
export type { FeedbackRequest } from './models/feedback-request';
export type { FeedbackResponse } from './models/feedback-response';
export type { FeedbackUpdateRequest } from './models/feedback-update-request';
export type { PageResponseBookResponse } from './models/page-response-book-response';
export type { PageResponseBorrowedBookResponse } from './models/page-response-borrowed-book-response';
export type { PageResponseFeedbackResponse } from './models/page-response-feedback-response';
export type { RegisterRequest } from './models/register-request';
export type { RegisterResponse } from './models/register-response';
