apiVersion: v1
kind: Secret
metadata:
  name: bsn-backend-secret
  namespace: bsn
type: Opaque
stringData:
  DB_USER: "bsnadmin"
  DB_PASSWORD: "REPLACE_ME_WITH_RDS_PASSWORD"
  JWT_SECRET_KEY: "REPLACE_ME_WITH_JWT_SECRET"
  MAIL_USERNAME: "REPLACE_ME_WITH_SMTP_USER"
  MAIL_PASSWORD: "REPLACE_ME_WITH_SMTP_PASSWORD"
