apiVersion: v1
kind: Secret
metadata:
  name: bsn-backend-secret
  namespace: bsn
type: Opaque
stringData:
  DB_USER: "bsnadmin"
  DB_PASSWORD: "BsnSecurePass2026#Db"
  JWT_SECRET_KEY: "HVH1a4Pke93rIXnnghrd4PeVnOC715IIbGUwowbt8+w="
  MAIL_USERNAME: "abdelatif.nabgha06@gmail.com"
  MAIL_PASSWORD: "password"

