/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookResponse } from './book-response';
export interface ApiResponseBookResponse {
  data?: BookResponse;
  message?: string;
}
