/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BorrowedBookResponse } from './borrowed-book-response';
export interface ApiResponseBorrowedBookResponse {
  data?: BorrowedBookResponse;
  message?: string;
}
