/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeedbackResponse } from './feedback-response';
export interface ApiResponseFeedbackResponse {
  data?: FeedbackResponse;
  message?: string;
}
