/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminStatsResponse } from './admin-stats-response';
export interface ApiResponseAdminStatsResponse {
  data?: AdminStatsResponse;
  message?: string;
}
