/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeedbackResponse {
  bookId?: number;
  comment?: string;
  id?: number;
  note?: number;
  ownFeedback?: boolean;
}
