spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  application:
    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration: ${JWT_EXPIRATION:86400000}
    mailing:
      frontend:
        activation-url: ${FRONTEND_ACTIVATION_URL}
    file:
      upload:
        photos-output-path: ${FILE_UPLOAD_PATH:/app/uploads}
    cors:
      allowed-origins:
        - ${FRONTEND_ORIGIN}

aws:
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}