/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseFeedbackResponse } from '../../models/api-response-feedback-response';
import { FeedbackUpdateRequest } from '../../models/feedback-update-request';

export interface UpdateFeedback$Params {
  feedbackId: number;
      body: FeedbackUpdateRequest
}

export function updateFeedback(http: HttpClient, rootUrl: string, params: UpdateFeedback$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseFeedbackResponse>> {
  const rb = new RequestBuilder(rootUrl, updateFeedback.PATH, 'patch');
  if (params) {
    rb.path('feedbackId', params.feedbackId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseFeedbackResponse>;
    })
  );
}

updateFeedback.PATH = '/feedbacks/{feedbackId}';
