create table _users
(
    id                 integer generated by default as identity primary key,
    account_locked     boolean      not null,
    birth_date         date,
    creation_date      timestamp(6) not null,
    created_by         integer,
    last_modified_date timestamp(6),
    last_modified_by   integer,
    email              varchar(255)
        constraint uk_users_email unique,
    enabled            boolean      not null,
    first_name         varchar(255),
    last_name          varchar(255),
    password           varchar(255)
);

alter table _users
    owner to postgres;

create table roles
(
    id         integer generated by default as identity primary key,
    created_at timestamp(6) not null,
    name       varchar(255)
        constraint uk_roles_name
            unique,
    updated_at timestamp(6)
);

alter table roles
    owner to postgres;

create table _users_roles
(
    users_id integer not null
        constraint fk_users_roles_users_id
            references _users,
    roles_id integer not null
        constraint fk_users_roles_roles_id
            references roles
);

alter table _users_roles
    owner to postgres;

create table tokens
(
    id           integer generated by default as identity
        primary key,
    created_at   timestamp(6),
    expired_at   timestamp(6),
    token        varchar(255),
    validated_at timestamp(6),
    user_id      integer not null
        constraint fk_tokens_user_id
            references _users
);

alter table tokens
    owner to postgres;

create table book
(
    id                 integer generated by default as identity
        primary key,
    created_by         integer,
    creation_date      timestamp(6) not null,
    last_modified_by   integer,
    last_modified_date timestamp(6),
    archived           boolean      not null,
    author             varchar(255),
    book_cover         varchar(255),
    isbn               varchar(255),
    shareable          boolean      not null,
    synopsis           varchar(255),
    title              varchar(255),
    owner_id           integer      not null
        constraint fk_book_owner_id
            references _users
);

alter table book
    owner to postgres;

create table book_transaction_history
(
    id                 integer generated by default as identity
        primary key,
    created_by         integer,
    creation_date      timestamp(6) not null,
    last_modified_by   integer,
    last_modified_date timestamp(6),
    returned           boolean      not null,
    returned_approved  boolean      not null,
    book_id            integer      not null
        constraint fk_book_transaction_history_book_id
            references book,
    user_id            integer      not null
        constraint fk_book_transaction_history_user_id
            references _users
);

alter table book_transaction_history
    owner to postgres;

create table feedback
(
    id                 integer generated by default as identity
        primary key,
    created_by         integer,
    creation_date      timestamp(6) not null,
    last_modified_by   integer,
    last_modified_date timestamp(6),
    comment            varchar(255),
    note               double precision,
    book_id            integer      not null
        constraint fk_feedback_book_id
            references book
);

alter table feedback
    owner to postgres;